name: Publish Alpha Build ...aX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "ovos_core/version.py"
      - "test/**"
      - "examples/**"
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "CHANGELOG.md"
      - "MANIFEST.in"
      - "readme.md"
      - "scripts/**"
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: openvoiceos/.github/.github/workflows/publish_alpha_release.yml@feat/shared_actions1
    secrets: inherit
    with:
      version_file: skill_randomness/version.py # File location of the version file, default: version.py
      python_version: "3.10"
      locale_folder: skill_randomness/locale
      update_intentfile: test/test_intents.yaml
      changelog_file: CHANGELOG.md
