name: skill_tests
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  py_build_tests:
    name: py_build_tests
    permissions:
      contents: read
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.10"
  skill_unit_tests:
    name: skill_unit_tests
    permissions:
      contents: read
    uses: neongeckocom/.github/.github/workflows/skill_tests.yml@master
    with:
      ovos_versions: '["3.10", "3.11"]'
