# This workflow will run unit tests

name: Run Unit Tests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'skill_randomness/version.py'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'skill_randomness/version.py'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
          python -m pip install -r requirements.txt
      - name: Install core repo
        run: |
          pip install -e .[extras]
      - name: Install test dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Run unittests
        run: |
          pytest --cov=ovos_utils --cov=skill_randomness --cov-report xml test/
          # NOTE: additional pytest invocations should also add the --cov-append flag
          #       or they will overwrite previous invocations' coverage reports
          #       (for an example, see OVOS Skill Manager's workflow)
      - name: Upload coverage
        if: "${{ matrix.python-version == '3.12' }}"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v3
